# Generated by Django 5.2.14 on 2026-05-16 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('RKO', 'Расчетно-кассовое обслуживание'), ('SALARY', 'Зарплатный проект'), ('ACQUIRING', 'Эквайринг')], max_length=20)),
                ('counterparty_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('image_key', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('balance_account_number', models.CharField(max_length=20)),
                ('currency_code', models.CharField(choices=[('810', 'RUB'), ('840', 'USD')], default='810', max_length=3)),
                ('assigned_account_number', models.CharField(blank=True, max_length=34, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('account_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_contracts', to='contracts.accountrequest')),
                ('bank_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.bankcontract')),
            ],
            options={
                'unique_together': {('account_request', 'bank_contract')},
            },
        ),
    ]
