# Generated by Django 5.2.14 on 2026-05-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcontract',
            name='price',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='primary_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_requests', to='contracts.bankcontract'),
        ),
    ]
