# Generated by Django 5.2.14 on 2026-05-17 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_bankcontract_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedcontract',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='requestedcontract',
            name='connection_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата подключения'),
        ),
    ]
