# Generated by Django 5.2.14 on 2026-05-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_requestedcontract_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='balance_account_number',
        ),
        migrations.RemoveField(
            model_name='requestedcontract',
            name='quantity',
        ),
    ]
